name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}
          VITE_API_URL: https://models.inference.ai.azure.com/chat/completions

      - name: Inject environment variables
        run: |
          sed -i "s|%VITE_GITHUB_API_TOKEN%|${{ secrets.API_TOKEN }}|g" dist/index.html
          sed -i "s|%VITE_API_URL%|https://models.inference.ai.azure.com/chat/completions|g" dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'